- heh-ui/src/app/pages/user-profile/user-profile.component.scss
> Heh-UI-16: Сhange component profile

- heh-ui/src/app/components/layouts/home-layout/home-layout.component.html
- heh-ui/src/app/components/layouts/home-layout/home-layout.component.ts
Fix bg images and titles to work without refreshing the page
> HEH-UI-18: Add titles to the page depending on the tab

- .gitignore
- heh-ui/src/app/components/discount-card/discount-card.component.html
- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.html
- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.scss
- heh-ui/src/app/pages/discounts/discounts.component.ts
Added conditions to discount card and label for promo code on discount details modal.
> HEH-UI-82: Added conditions to discount card and label for promo code

- heh-ui/src/app/pages/moderator/categories-tags/categories-tags.component.html
- heh-ui/src/app/pages/moderator/categories-tags/categories-tags.component.scss
- heh-ui/src/app/pages/moderator/categories-tags/categories-tags.component.ts
- heh-ui/src/app/pages/moderator/categories-tags/list-input/list-input.component.html
- heh-ui/src/app/pages/moderator/categories-tags/list-input/list-input.component.scss
- heh-ui/src/app/pages/moderator/categories-tags/list-input/list-input.component.ts
> HEH-UI-81: Add real data to categories and tags

- heh-ui/src/app/components/discount-card/discount-card.component.html
- heh-ui/src/app/components/discount-card/discount-card.component.scss
- heh-ui/src/app/components/user-card/user-card.component.html
- heh-ui/src/app/components/user-card/user-card.component.ts
- heh-ui/src/app/pages/admin/users/users.service.ts
- heh-ui/src/app/pages/discounts/discounts.service.ts
- heh-ui/src/app/pages/moderator/vendors/vendor-card/vendor-card.component.html
- heh-ui/src/app/pages/moderator/vendors/vendor-card/vendor-card.component.scss
Rename classes for discount and vendor cards
> HEH-UI-91: Added request for changing user's role and state

- heh-ui/src/app/components/favorite-card/favorite-card.component.ts
- heh-ui/src/app/pages/favorites/favorites.component.html
- heh-ui/src/app/pages/favorites/favorites.component.ts
Add getFavorite request after deleting item
> HEH-UI-85: Add post, put and delete requests to favorites

- heh-ui/src/app/pages/favorites/edit-note-modal/edit-note-modal.component.html
- heh-ui/src/app/pages/favorites/edit-note-modal/edit-note-modal.component.scss
Add dialog close to submit button
Fix bug fith cancel button
> HEH-UI-95: Fix bugs on favorites modal

- heh-ui/src/app/app.module.ts
- heh-ui/src/app/components/confirmation-dialog/confirmation-dialog.component.html
- heh-ui/src/app/components/confirmation-dialog/confirmation-dialog.component.scss
- heh-ui/src/app/components/confirmation-dialog/confirmation-dialog.component.spec.ts
- heh-ui/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
- heh-ui/src/app/components/favorite-card/favorite-card.component.ts
- heh-ui/src/app/pages/admin/event-history/event-history.component.ts
- heh-ui/src/app/pages/admin/event-history/history.service.ts
- heh-ui/src/app/pages/favorites/favorites.component.ts
- heh-ui/src/app/pages/favorites/favorites.service.ts
- heh-ui/src/app/pages/moderator/categories-tags/list-input/list-input.component.ts
- heh-ui/src/app/pages/moderator/vendors/add-vendor-modal/edit-discount-card/edit-discount-card.component.html
- heh-ui/src/app/pages/moderator/vendors/add-vendor-modal/edit-discount-card/edit-discount-card.component.ts
- heh-ui/src/app/pages/moderator/vendors/add-vendor-modal/model-list-input/add-address/add-address.component.scss
- heh-ui/src/app/pages/moderator/vendors/vendor-card/vendor-card.component.ts
- heh-ui/src/app/services/modal-service/modal.service.ts
> HEH-UI-128: Confirmation dialog was added, request links were changed to odata

- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.html
- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.ts
- heh-ui/src/app/pages/favorites/favorites.component.ts
Fixed minor issue for favorites updateAfterDelete function
> HEH-UI-135: Added condition for addresses dropdown and map. 

- heh-ui/src/app/components/page-search/page-search.component.html
- heh-ui/src/app/pages/admin/statistics/statistics.component.html
- heh-ui/src/app/pages/admin/statistics/statistics.component.ts
- heh-ui/src/app/pages/admin/statistics/statistics.service.ts
- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.html
- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.scss
- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.ts
- heh-ui/src/app/pages/discounts/discounts.service.ts
- heh-ui/src/app/services/modal-service/modal.service.ts
HEH-UI-136: Add discount modal opening in statistics page
> HEH-UI-108: Add filters to statistics page

- heh-ui/src/app/components/layouts/home-layout/home-layout.component.scss
- heh-ui/src/app/components/page-search/page-search.component.scss
- heh-ui/src/app/pages/moderator/vendors/vendors.component.html
- heh-ui/src/app/pages/moderator/vendors/vendors.component.ts
search component became adaptive too
> HEH-UI-137: Made vendors page adaptive

- heh-ui/src/app/pages/moderator/vendors/vendor.service.ts
- heh-ui/src/app/pages/moderator/vendors/vendors.component.html
- heh-ui/src/app/pages/moderator/vendors/vendors.component.ts
- heh-ui/src/app/services/filter-service/filters.service.ts
> HEH-UI-104: add filters to vendors

- heh-ui/src/app/components/favorite-card/favorite-card.component.html
- heh-ui/src/app/components/favorite-card/favorite-card.component.scss
- heh-ui/src/app/pages/admin/statistics/statistics.component.ts
- heh-ui/src/app/pages/discounts/discounts.component.html
- heh-ui/src/app/pages/discounts/discounts.component.ts
- heh-ui/src/app/pages/moderator/vendors/vendors.component.html
- heh-ui/src/app/pages/moderator/vendors/vendors.component.ts
- heh-ui/src/app/services/grid-service/grid.service.spec.ts
- heh-ui/src/app/services/grid-service/grid.service.ts
Created additional service for the adaptive grid. Fixed vendors page after merging with development (last merge on develop rewrote vendors component in a wrong way). Fixed reassignment issue related to class names on favorite card
> HEH-UI-145: Added adaptive functionality for discounts.

- heh-ui/src/app/app-routing.module.ts
- heh-ui/src/app/app.module.ts
- heh-ui/src/app/components/header/header.component.ts
- heh-ui/src/app/components/layouts/home-layout/home-layout.component.ts
- heh-ui/src/app/models/event-notification-element.ts
- heh-ui/src/app/models/tab.ts
- heh-ui/src/app/pages/admin/statistics/statistics.component.ts
- heh-ui/src/app/pages/notifications/notifications.component.html
- heh-ui/src/app/pages/notifications/notifications.component.scss
- heh-ui/src/app/pages/notifications/notifications.component.spec.ts
- heh-ui/src/app/pages/notifications/notifications.component.ts
- heh-ui/src/assets/i18n/en.json
- heh-ui/src/assets/i18n/ru.json
Also created component for it. Didn`t remove commented code, because it might be useful once we will start gathering data from BE.
> HEH-UI-147: Added notification tab on header

- heh-ui/src/app/components/layouts/home-layout/home-layout.component.html
> HEH-UI-160: Bug with spinner on add discount modal

- heh-ui/src/app/pages/favorites/edit-note-modal/edit-note-modal.component.html
- heh-ui/src/app/pages/favorites/edit-note-modal/edit-note-modal.component.ts
- heh-ui/src/app/services/modal-service/modal.service.ts
> HEH-UI-161: Dug with favorite notes text

- heh-ui/src/app/services/filter-service/filters.service.ts
> HEH-UI-171: Bug with vendor filter

- heh-ui/src/app/components/favorite-card/favorite-card.component.html
- heh-ui/src/app/components/favorite-card/favorite-card.component.ts
- heh-ui/src/app/pages/admin/statistics/statistics.component.ts
- heh-ui/src/app/pages/discounts/discounts.component.ts
- heh-ui/src/app/pages/favorites/favorites.component.ts
- heh-ui/src/app/services/modal-service/modal.service.ts
> HEH-UI-192: Statistics bug was fixed

- heh-ui/src/styles.scss
> HEH-UI-184: Input border color was changed

- heh-ui/src/app/pages/discounts/discount-details-modal/discount-details-modal.component.ts
- heh-ui/src/app/pages/discounts/discount-details-modal/geocode.service.ts
- heh-ui/src/app/pages/notifications/notifications.component.html
> HEH-UI-203: Fix bug with map

- heh-ui/src/app/pages/admin/statistics/statistics.component.ts
> HEH-UI-204: Excel file name was changed

- heh-ui/src/app/services/spinner-service/spinner-interceptor.ts
> HEH-UI-208: Bug with spinner
